<?php
// $Id: node_service.module,v 1.5.2.21.2.4 2010/02/28 01:15:31 heyrocker Exp $
/**
 * @file
 *  Link general node functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function mwc_service_perm() {
  return array(
    'load mwc data',
  );
}

/**
 * Implementation of hook_service().
 */
function mwc_service_service() {
  return array(

    // node.get
    array(
      '#method'           => 'mwc.get',
      '#callback'         => 'mwc_service_get',
      '#access callback'  => 'mwc_service_get_access',
      '#file'             => array('file' => 'inc', 'module' => 'mwc_service'),
      '#args'             => array(
        array(
          '#name'           => 'nid',
          '#type'           => 'int',
          '#description'    => t('A node ID.')),
        array(
          '#name'           => 'fields',
          '#type'           => 'array',
          '#optional'       => TRUE,
          '#description'    => t('A list of fields to return.'))),
      '#return'           => 'struct',
      '#help'             => t('Returns a node data.')),
    
    // node.view

    
    // node.save
   

    // node.delete

  );
}